/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package net.sareweb.txotx.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import net.sareweb.txotx.model.Gertaera;
import net.sareweb.txotx.model.GertaeraModel;
import net.sareweb.txotx.model.GertaeraSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Gertaera service. Represents a row in the &quot;Txotx_Gertaera&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link net.sareweb.txotx.model.GertaeraModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GertaeraImpl}.
 * </p>
 *
 * @author A.Galdos
 * @see GertaeraImpl
 * @see net.sareweb.txotx.model.Gertaera
 * @see net.sareweb.txotx.model.GertaeraModel
 * @generated
 */
@JSON(strict = true)
public class GertaeraModelImpl extends BaseModelImpl<Gertaera>
	implements GertaeraModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a gertaera model instance should use the {@link net.sareweb.txotx.model.Gertaera} interface instead.
	 */
	public static final String TABLE_NAME = "Txotx_Gertaera";
	public static final Object[][] TABLE_COLUMNS = {
			{ "gertaeraId", Types.BIGINT },
			{ "sagardotegiId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "screenName", Types.VARCHAR },
			{ "gertaeraMota", Types.VARCHAR },
			{ "testua", Types.VARCHAR },
			{ "irudiKarpetaId", Types.BIGINT },
			{ "irudia", Types.VARCHAR },
			{ "balorazioa", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table Txotx_Gertaera (gertaeraId LONG not null primary key,sagardotegiId LONG,userId LONG,screenName VARCHAR(75) null,gertaeraMota VARCHAR(75) null,testua VARCHAR(75) null,irudiKarpetaId LONG,irudia VARCHAR(75) null,balorazioa LONG,createDate DATE null,modifiedDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table Txotx_Gertaera";
	public static final String ORDER_BY_JPQL = " ORDER BY gertaera.createDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY Txotx_Gertaera.createDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.net.sareweb.txotx.model.Gertaera"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.net.sareweb.txotx.model.Gertaera"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Gertaera toModel(GertaeraSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Gertaera model = new GertaeraImpl();

		model.setGertaeraId(soapModel.getGertaeraId());
		model.setSagardotegiId(soapModel.getSagardotegiId());
		model.setUserId(soapModel.getUserId());
		model.setScreenName(soapModel.getScreenName());
		model.setGertaeraMota(soapModel.getGertaeraMota());
		model.setTestua(soapModel.getTestua());
		model.setIrudiKarpetaId(soapModel.getIrudiKarpetaId());
		model.setIrudia(soapModel.getIrudia());
		model.setBalorazioa(soapModel.getBalorazioa());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Gertaera> toModels(GertaeraSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Gertaera> models = new ArrayList<Gertaera>(soapModels.length);

		for (GertaeraSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.net.sareweb.txotx.model.Gertaera"));

	public GertaeraModelImpl() {
	}

	public long getPrimaryKey() {
		return _gertaeraId;
	}

	public void setPrimaryKey(long primaryKey) {
		setGertaeraId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_gertaeraId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return Gertaera.class;
	}

	public String getModelClassName() {
		return Gertaera.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("gertaeraId", getGertaeraId());
		attributes.put("sagardotegiId", getSagardotegiId());
		attributes.put("userId", getUserId());
		attributes.put("screenName", getScreenName());
		attributes.put("gertaeraMota", getGertaeraMota());
		attributes.put("testua", getTestua());
		attributes.put("irudiKarpetaId", getIrudiKarpetaId());
		attributes.put("irudia", getIrudia());
		attributes.put("balorazioa", getBalorazioa());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long gertaeraId = (Long)attributes.get("gertaeraId");

		if (gertaeraId != null) {
			setGertaeraId(gertaeraId);
		}

		Long sagardotegiId = (Long)attributes.get("sagardotegiId");

		if (sagardotegiId != null) {
			setSagardotegiId(sagardotegiId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String screenName = (String)attributes.get("screenName");

		if (screenName != null) {
			setScreenName(screenName);
		}

		String gertaeraMota = (String)attributes.get("gertaeraMota");

		if (gertaeraMota != null) {
			setGertaeraMota(gertaeraMota);
		}

		String testua = (String)attributes.get("testua");

		if (testua != null) {
			setTestua(testua);
		}

		Long irudiKarpetaId = (Long)attributes.get("irudiKarpetaId");

		if (irudiKarpetaId != null) {
			setIrudiKarpetaId(irudiKarpetaId);
		}

		String irudia = (String)attributes.get("irudia");

		if (irudia != null) {
			setIrudia(irudia);
		}

		Long balorazioa = (Long)attributes.get("balorazioa");

		if (balorazioa != null) {
			setBalorazioa(balorazioa);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}
	}

	@JSON
	public long getGertaeraId() {
		return _gertaeraId;
	}

	public void setGertaeraId(long gertaeraId) {
		_gertaeraId = gertaeraId;
	}

	@JSON
	public long getSagardotegiId() {
		return _sagardotegiId;
	}

	public void setSagardotegiId(long sagardotegiId) {
		_sagardotegiId = sagardotegiId;
	}

	@JSON
	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	public String getScreenName() {
		if (_screenName == null) {
			return StringPool.BLANK;
		}
		else {
			return _screenName;
		}
	}

	public void setScreenName(String screenName) {
		_screenName = screenName;
	}

	@JSON
	public String getGertaeraMota() {
		if (_gertaeraMota == null) {
			return StringPool.BLANK;
		}
		else {
			return _gertaeraMota;
		}
	}

	public void setGertaeraMota(String gertaeraMota) {
		_gertaeraMota = gertaeraMota;
	}

	@JSON
	public String getTestua() {
		if (_testua == null) {
			return StringPool.BLANK;
		}
		else {
			return _testua;
		}
	}

	public void setTestua(String testua) {
		_testua = testua;
	}

	@JSON
	public long getIrudiKarpetaId() {
		return _irudiKarpetaId;
	}

	public void setIrudiKarpetaId(long irudiKarpetaId) {
		_irudiKarpetaId = irudiKarpetaId;
	}

	@JSON
	public String getIrudia() {
		if (_irudia == null) {
			return StringPool.BLANK;
		}
		else {
			return _irudia;
		}
	}

	public void setIrudia(String irudia) {
		_irudia = irudia;
	}

	@JSON
	public long getBalorazioa() {
		return _balorazioa;
	}

	public void setBalorazioa(long balorazioa) {
		_balorazioa = balorazioa;
	}

	@JSON
	public Date getCreateDate() {
		return _createDate;
	}

	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Gertaera.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Gertaera toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (Gertaera)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		GertaeraImpl gertaeraImpl = new GertaeraImpl();

		gertaeraImpl.setGertaeraId(getGertaeraId());
		gertaeraImpl.setSagardotegiId(getSagardotegiId());
		gertaeraImpl.setUserId(getUserId());
		gertaeraImpl.setScreenName(getScreenName());
		gertaeraImpl.setGertaeraMota(getGertaeraMota());
		gertaeraImpl.setTestua(getTestua());
		gertaeraImpl.setIrudiKarpetaId(getIrudiKarpetaId());
		gertaeraImpl.setIrudia(getIrudia());
		gertaeraImpl.setBalorazioa(getBalorazioa());
		gertaeraImpl.setCreateDate(getCreateDate());
		gertaeraImpl.setModifiedDate(getModifiedDate());

		gertaeraImpl.resetOriginalValues();

		return gertaeraImpl;
	}

	public int compareTo(Gertaera gertaera) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(), gertaera.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		Gertaera gertaera = null;

		try {
			gertaera = (Gertaera)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = gertaera.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Gertaera> toCacheModel() {
		GertaeraCacheModel gertaeraCacheModel = new GertaeraCacheModel();

		gertaeraCacheModel.gertaeraId = getGertaeraId();

		gertaeraCacheModel.sagardotegiId = getSagardotegiId();

		gertaeraCacheModel.userId = getUserId();

		gertaeraCacheModel.screenName = getScreenName();

		String screenName = gertaeraCacheModel.screenName;

		if ((screenName != null) && (screenName.length() == 0)) {
			gertaeraCacheModel.screenName = null;
		}

		gertaeraCacheModel.gertaeraMota = getGertaeraMota();

		String gertaeraMota = gertaeraCacheModel.gertaeraMota;

		if ((gertaeraMota != null) && (gertaeraMota.length() == 0)) {
			gertaeraCacheModel.gertaeraMota = null;
		}

		gertaeraCacheModel.testua = getTestua();

		String testua = gertaeraCacheModel.testua;

		if ((testua != null) && (testua.length() == 0)) {
			gertaeraCacheModel.testua = null;
		}

		gertaeraCacheModel.irudiKarpetaId = getIrudiKarpetaId();

		gertaeraCacheModel.irudia = getIrudia();

		String irudia = gertaeraCacheModel.irudia;

		if ((irudia != null) && (irudia.length() == 0)) {
			gertaeraCacheModel.irudia = null;
		}

		gertaeraCacheModel.balorazioa = getBalorazioa();

		Date createDate = getCreateDate();

		if (createDate != null) {
			gertaeraCacheModel.createDate = createDate.getTime();
		}
		else {
			gertaeraCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			gertaeraCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			gertaeraCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return gertaeraCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{gertaeraId=");
		sb.append(getGertaeraId());
		sb.append(", sagardotegiId=");
		sb.append(getSagardotegiId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", screenName=");
		sb.append(getScreenName());
		sb.append(", gertaeraMota=");
		sb.append(getGertaeraMota());
		sb.append(", testua=");
		sb.append(getTestua());
		sb.append(", irudiKarpetaId=");
		sb.append(getIrudiKarpetaId());
		sb.append(", irudia=");
		sb.append(getIrudia());
		sb.append(", balorazioa=");
		sb.append(getBalorazioa());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("net.sareweb.txotx.model.Gertaera");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>gertaeraId</column-name><column-value><![CDATA[");
		sb.append(getGertaeraId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sagardotegiId</column-name><column-value><![CDATA[");
		sb.append(getSagardotegiId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>screenName</column-name><column-value><![CDATA[");
		sb.append(getScreenName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>gertaeraMota</column-name><column-value><![CDATA[");
		sb.append(getGertaeraMota());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>testua</column-name><column-value><![CDATA[");
		sb.append(getTestua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>irudiKarpetaId</column-name><column-value><![CDATA[");
		sb.append(getIrudiKarpetaId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>irudia</column-name><column-value><![CDATA[");
		sb.append(getIrudia());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>balorazioa</column-name><column-value><![CDATA[");
		sb.append(getBalorazioa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Gertaera.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			Gertaera.class
		};
	private long _gertaeraId;
	private long _sagardotegiId;
	private long _userId;
	private String _userUuid;
	private String _screenName;
	private String _gertaeraMota;
	private String _testua;
	private long _irudiKarpetaId;
	private String _irudia;
	private long _balorazioa;
	private Date _createDate;
	private Date _modifiedDate;
	private Gertaera _escapedModelProxy;
}