/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package net.sareweb.txotx.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import net.sareweb.txotx.model.Oharra;
import net.sareweb.txotx.service.OharraLocalServiceUtil;

/**
 * The extended model base implementation for the Oharra service. Represents a row in the &quot;Txotx_Oharra&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OharraImpl}.
 * </p>
 *
 * @author A.Galdos
 * @see OharraImpl
 * @see net.sareweb.txotx.model.Oharra
 * @generated
 */
public abstract class OharraBaseImpl extends OharraModelImpl implements Oharra {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a oharra model instance should use the {@link Oharra} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			OharraLocalServiceUtil.addOharra(this);
		}
		else {
			OharraLocalServiceUtil.updateOharra(this);
		}
	}
}