/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package net.sareweb.txotx.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import net.sareweb.txotx.model.Sagardotegi;
import net.sareweb.txotx.model.SagardotegiModel;
import net.sareweb.txotx.model.SagardotegiSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Sagardotegi service. Represents a row in the &quot;Txotx_Sagardotegi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link net.sareweb.txotx.model.SagardotegiModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SagardotegiImpl}.
 * </p>
 *
 * @author A.Galdos
 * @see SagardotegiImpl
 * @see net.sareweb.txotx.model.Sagardotegi
 * @see net.sareweb.txotx.model.SagardotegiModel
 * @generated
 */
@JSON(strict = true)
public class SagardotegiModelImpl extends BaseModelImpl<Sagardotegi>
	implements SagardotegiModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a sagardotegi model instance should use the {@link net.sareweb.txotx.model.Sagardotegi} interface instead.
	 */
	public static final String TABLE_NAME = "Txotx_Sagardotegi";
	public static final Object[][] TABLE_COLUMNS = {
			{ "sagardotegiId", Types.BIGINT },
			{ "izena", Types.VARCHAR },
			{ "herria", Types.VARCHAR },
			{ "helbidea", Types.VARCHAR },
			{ "telefonoa", Types.VARCHAR },
			{ "emaila", Types.VARCHAR },
			{ "weborria", Types.VARCHAR },
			{ "lat", Types.DOUBLE },
			{ "lng", Types.DOUBLE },
			{ "edukiera", Types.BIGINT },
			{ "irudiKarpetaId", Types.BIGINT },
			{ "irudia", Types.VARCHAR },
			{ "irudiKopurua", Types.BIGINT },
			{ "iruzkinKopurua", Types.BIGINT },
			{ "balorazioKopurua", Types.BIGINT },
			{ "balorazioenBB", Types.DOUBLE },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table Txotx_Sagardotegi (sagardotegiId LONG not null primary key,izena VARCHAR(75) null,herria VARCHAR(75) null,helbidea VARCHAR(75) null,telefonoa VARCHAR(75) null,emaila VARCHAR(75) null,weborria VARCHAR(75) null,lat DOUBLE,lng DOUBLE,edukiera LONG,irudiKarpetaId LONG,irudia VARCHAR(75) null,irudiKopurua LONG,iruzkinKopurua LONG,balorazioKopurua LONG,balorazioenBB DOUBLE,createDate DATE null,modifiedDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table Txotx_Sagardotegi";
	public static final String ORDER_BY_JPQL = " ORDER BY sagardotegi.createDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY Txotx_Sagardotegi.createDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.net.sareweb.txotx.model.Sagardotegi"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.net.sareweb.txotx.model.Sagardotegi"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Sagardotegi toModel(SagardotegiSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Sagardotegi model = new SagardotegiImpl();

		model.setSagardotegiId(soapModel.getSagardotegiId());
		model.setIzena(soapModel.getIzena());
		model.setHerria(soapModel.getHerria());
		model.setHelbidea(soapModel.getHelbidea());
		model.setTelefonoa(soapModel.getTelefonoa());
		model.setEmaila(soapModel.getEmaila());
		model.setWeborria(soapModel.getWeborria());
		model.setLat(soapModel.getLat());
		model.setLng(soapModel.getLng());
		model.setEdukiera(soapModel.getEdukiera());
		model.setIrudiKarpetaId(soapModel.getIrudiKarpetaId());
		model.setIrudia(soapModel.getIrudia());
		model.setIrudiKopurua(soapModel.getIrudiKopurua());
		model.setIruzkinKopurua(soapModel.getIruzkinKopurua());
		model.setBalorazioKopurua(soapModel.getBalorazioKopurua());
		model.setBalorazioenBB(soapModel.getBalorazioenBB());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Sagardotegi> toModels(SagardotegiSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Sagardotegi> models = new ArrayList<Sagardotegi>(soapModels.length);

		for (SagardotegiSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.net.sareweb.txotx.model.Sagardotegi"));

	public SagardotegiModelImpl() {
	}

	public long getPrimaryKey() {
		return _sagardotegiId;
	}

	public void setPrimaryKey(long primaryKey) {
		setSagardotegiId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_sagardotegiId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return Sagardotegi.class;
	}

	public String getModelClassName() {
		return Sagardotegi.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("sagardotegiId", getSagardotegiId());
		attributes.put("izena", getIzena());
		attributes.put("herria", getHerria());
		attributes.put("helbidea", getHelbidea());
		attributes.put("telefonoa", getTelefonoa());
		attributes.put("emaila", getEmaila());
		attributes.put("weborria", getWeborria());
		attributes.put("lat", getLat());
		attributes.put("lng", getLng());
		attributes.put("edukiera", getEdukiera());
		attributes.put("irudiKarpetaId", getIrudiKarpetaId());
		attributes.put("irudia", getIrudia());
		attributes.put("irudiKopurua", getIrudiKopurua());
		attributes.put("iruzkinKopurua", getIruzkinKopurua());
		attributes.put("balorazioKopurua", getBalorazioKopurua());
		attributes.put("balorazioenBB", getBalorazioenBB());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long sagardotegiId = (Long)attributes.get("sagardotegiId");

		if (sagardotegiId != null) {
			setSagardotegiId(sagardotegiId);
		}

		String izena = (String)attributes.get("izena");

		if (izena != null) {
			setIzena(izena);
		}

		String herria = (String)attributes.get("herria");

		if (herria != null) {
			setHerria(herria);
		}

		String helbidea = (String)attributes.get("helbidea");

		if (helbidea != null) {
			setHelbidea(helbidea);
		}

		String telefonoa = (String)attributes.get("telefonoa");

		if (telefonoa != null) {
			setTelefonoa(telefonoa);
		}

		String emaila = (String)attributes.get("emaila");

		if (emaila != null) {
			setEmaila(emaila);
		}

		String weborria = (String)attributes.get("weborria");

		if (weborria != null) {
			setWeborria(weborria);
		}

		Double lat = (Double)attributes.get("lat");

		if (lat != null) {
			setLat(lat);
		}

		Double lng = (Double)attributes.get("lng");

		if (lng != null) {
			setLng(lng);
		}

		Long edukiera = (Long)attributes.get("edukiera");

		if (edukiera != null) {
			setEdukiera(edukiera);
		}

		Long irudiKarpetaId = (Long)attributes.get("irudiKarpetaId");

		if (irudiKarpetaId != null) {
			setIrudiKarpetaId(irudiKarpetaId);
		}

		String irudia = (String)attributes.get("irudia");

		if (irudia != null) {
			setIrudia(irudia);
		}

		Long irudiKopurua = (Long)attributes.get("irudiKopurua");

		if (irudiKopurua != null) {
			setIrudiKopurua(irudiKopurua);
		}

		Long iruzkinKopurua = (Long)attributes.get("iruzkinKopurua");

		if (iruzkinKopurua != null) {
			setIruzkinKopurua(iruzkinKopurua);
		}

		Long balorazioKopurua = (Long)attributes.get("balorazioKopurua");

		if (balorazioKopurua != null) {
			setBalorazioKopurua(balorazioKopurua);
		}

		Double balorazioenBB = (Double)attributes.get("balorazioenBB");

		if (balorazioenBB != null) {
			setBalorazioenBB(balorazioenBB);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}
	}

	@JSON
	public long getSagardotegiId() {
		return _sagardotegiId;
	}

	public void setSagardotegiId(long sagardotegiId) {
		_sagardotegiId = sagardotegiId;
	}

	@JSON
	public String getIzena() {
		if (_izena == null) {
			return StringPool.BLANK;
		}
		else {
			return _izena;
		}
	}

	public void setIzena(String izena) {
		_izena = izena;
	}

	@JSON
	public String getHerria() {
		if (_herria == null) {
			return StringPool.BLANK;
		}
		else {
			return _herria;
		}
	}

	public void setHerria(String herria) {
		_herria = herria;
	}

	@JSON
	public String getHelbidea() {
		if (_helbidea == null) {
			return StringPool.BLANK;
		}
		else {
			return _helbidea;
		}
	}

	public void setHelbidea(String helbidea) {
		_helbidea = helbidea;
	}

	@JSON
	public String getTelefonoa() {
		if (_telefonoa == null) {
			return StringPool.BLANK;
		}
		else {
			return _telefonoa;
		}
	}

	public void setTelefonoa(String telefonoa) {
		_telefonoa = telefonoa;
	}

	@JSON
	public String getEmaila() {
		if (_emaila == null) {
			return StringPool.BLANK;
		}
		else {
			return _emaila;
		}
	}

	public void setEmaila(String emaila) {
		_emaila = emaila;
	}

	@JSON
	public String getWeborria() {
		if (_weborria == null) {
			return StringPool.BLANK;
		}
		else {
			return _weborria;
		}
	}

	public void setWeborria(String weborria) {
		_weborria = weborria;
	}

	@JSON
	public double getLat() {
		return _lat;
	}

	public void setLat(double lat) {
		_lat = lat;
	}

	@JSON
	public double getLng() {
		return _lng;
	}

	public void setLng(double lng) {
		_lng = lng;
	}

	@JSON
	public long getEdukiera() {
		return _edukiera;
	}

	public void setEdukiera(long edukiera) {
		_edukiera = edukiera;
	}

	@JSON
	public long getIrudiKarpetaId() {
		return _irudiKarpetaId;
	}

	public void setIrudiKarpetaId(long irudiKarpetaId) {
		_irudiKarpetaId = irudiKarpetaId;
	}

	@JSON
	public String getIrudia() {
		if (_irudia == null) {
			return StringPool.BLANK;
		}
		else {
			return _irudia;
		}
	}

	public void setIrudia(String irudia) {
		_irudia = irudia;
	}

	@JSON
	public long getIrudiKopurua() {
		return _irudiKopurua;
	}

	public void setIrudiKopurua(long irudiKopurua) {
		_irudiKopurua = irudiKopurua;
	}

	@JSON
	public long getIruzkinKopurua() {
		return _iruzkinKopurua;
	}

	public void setIruzkinKopurua(long iruzkinKopurua) {
		_iruzkinKopurua = iruzkinKopurua;
	}

	@JSON
	public long getBalorazioKopurua() {
		return _balorazioKopurua;
	}

	public void setBalorazioKopurua(long balorazioKopurua) {
		_balorazioKopurua = balorazioKopurua;
	}

	@JSON
	public double getBalorazioenBB() {
		return _balorazioenBB;
	}

	public void setBalorazioenBB(double balorazioenBB) {
		_balorazioenBB = balorazioenBB;
	}

	@JSON
	public Date getCreateDate() {
		return _createDate;
	}

	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Sagardotegi.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Sagardotegi toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (Sagardotegi)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		SagardotegiImpl sagardotegiImpl = new SagardotegiImpl();

		sagardotegiImpl.setSagardotegiId(getSagardotegiId());
		sagardotegiImpl.setIzena(getIzena());
		sagardotegiImpl.setHerria(getHerria());
		sagardotegiImpl.setHelbidea(getHelbidea());
		sagardotegiImpl.setTelefonoa(getTelefonoa());
		sagardotegiImpl.setEmaila(getEmaila());
		sagardotegiImpl.setWeborria(getWeborria());
		sagardotegiImpl.setLat(getLat());
		sagardotegiImpl.setLng(getLng());
		sagardotegiImpl.setEdukiera(getEdukiera());
		sagardotegiImpl.setIrudiKarpetaId(getIrudiKarpetaId());
		sagardotegiImpl.setIrudia(getIrudia());
		sagardotegiImpl.setIrudiKopurua(getIrudiKopurua());
		sagardotegiImpl.setIruzkinKopurua(getIruzkinKopurua());
		sagardotegiImpl.setBalorazioKopurua(getBalorazioKopurua());
		sagardotegiImpl.setBalorazioenBB(getBalorazioenBB());
		sagardotegiImpl.setCreateDate(getCreateDate());
		sagardotegiImpl.setModifiedDate(getModifiedDate());

		sagardotegiImpl.resetOriginalValues();

		return sagardotegiImpl;
	}

	public int compareTo(Sagardotegi sagardotegi) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(), sagardotegi.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		Sagardotegi sagardotegi = null;

		try {
			sagardotegi = (Sagardotegi)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = sagardotegi.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Sagardotegi> toCacheModel() {
		SagardotegiCacheModel sagardotegiCacheModel = new SagardotegiCacheModel();

		sagardotegiCacheModel.sagardotegiId = getSagardotegiId();

		sagardotegiCacheModel.izena = getIzena();

		String izena = sagardotegiCacheModel.izena;

		if ((izena != null) && (izena.length() == 0)) {
			sagardotegiCacheModel.izena = null;
		}

		sagardotegiCacheModel.herria = getHerria();

		String herria = sagardotegiCacheModel.herria;

		if ((herria != null) && (herria.length() == 0)) {
			sagardotegiCacheModel.herria = null;
		}

		sagardotegiCacheModel.helbidea = getHelbidea();

		String helbidea = sagardotegiCacheModel.helbidea;

		if ((helbidea != null) && (helbidea.length() == 0)) {
			sagardotegiCacheModel.helbidea = null;
		}

		sagardotegiCacheModel.telefonoa = getTelefonoa();

		String telefonoa = sagardotegiCacheModel.telefonoa;

		if ((telefonoa != null) && (telefonoa.length() == 0)) {
			sagardotegiCacheModel.telefonoa = null;
		}

		sagardotegiCacheModel.emaila = getEmaila();

		String emaila = sagardotegiCacheModel.emaila;

		if ((emaila != null) && (emaila.length() == 0)) {
			sagardotegiCacheModel.emaila = null;
		}

		sagardotegiCacheModel.weborria = getWeborria();

		String weborria = sagardotegiCacheModel.weborria;

		if ((weborria != null) && (weborria.length() == 0)) {
			sagardotegiCacheModel.weborria = null;
		}

		sagardotegiCacheModel.lat = getLat();

		sagardotegiCacheModel.lng = getLng();

		sagardotegiCacheModel.edukiera = getEdukiera();

		sagardotegiCacheModel.irudiKarpetaId = getIrudiKarpetaId();

		sagardotegiCacheModel.irudia = getIrudia();

		String irudia = sagardotegiCacheModel.irudia;

		if ((irudia != null) && (irudia.length() == 0)) {
			sagardotegiCacheModel.irudia = null;
		}

		sagardotegiCacheModel.irudiKopurua = getIrudiKopurua();

		sagardotegiCacheModel.iruzkinKopurua = getIruzkinKopurua();

		sagardotegiCacheModel.balorazioKopurua = getBalorazioKopurua();

		sagardotegiCacheModel.balorazioenBB = getBalorazioenBB();

		Date createDate = getCreateDate();

		if (createDate != null) {
			sagardotegiCacheModel.createDate = createDate.getTime();
		}
		else {
			sagardotegiCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			sagardotegiCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			sagardotegiCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return sagardotegiCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(37);

		sb.append("{sagardotegiId=");
		sb.append(getSagardotegiId());
		sb.append(", izena=");
		sb.append(getIzena());
		sb.append(", herria=");
		sb.append(getHerria());
		sb.append(", helbidea=");
		sb.append(getHelbidea());
		sb.append(", telefonoa=");
		sb.append(getTelefonoa());
		sb.append(", emaila=");
		sb.append(getEmaila());
		sb.append(", weborria=");
		sb.append(getWeborria());
		sb.append(", lat=");
		sb.append(getLat());
		sb.append(", lng=");
		sb.append(getLng());
		sb.append(", edukiera=");
		sb.append(getEdukiera());
		sb.append(", irudiKarpetaId=");
		sb.append(getIrudiKarpetaId());
		sb.append(", irudia=");
		sb.append(getIrudia());
		sb.append(", irudiKopurua=");
		sb.append(getIrudiKopurua());
		sb.append(", iruzkinKopurua=");
		sb.append(getIruzkinKopurua());
		sb.append(", balorazioKopurua=");
		sb.append(getBalorazioKopurua());
		sb.append(", balorazioenBB=");
		sb.append(getBalorazioenBB());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(58);

		sb.append("<model><model-name>");
		sb.append("net.sareweb.txotx.model.Sagardotegi");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>sagardotegiId</column-name><column-value><![CDATA[");
		sb.append(getSagardotegiId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>izena</column-name><column-value><![CDATA[");
		sb.append(getIzena());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>herria</column-name><column-value><![CDATA[");
		sb.append(getHerria());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>helbidea</column-name><column-value><![CDATA[");
		sb.append(getHelbidea());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>telefonoa</column-name><column-value><![CDATA[");
		sb.append(getTelefonoa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>emaila</column-name><column-value><![CDATA[");
		sb.append(getEmaila());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>weborria</column-name><column-value><![CDATA[");
		sb.append(getWeborria());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lat</column-name><column-value><![CDATA[");
		sb.append(getLat());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lng</column-name><column-value><![CDATA[");
		sb.append(getLng());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>edukiera</column-name><column-value><![CDATA[");
		sb.append(getEdukiera());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>irudiKarpetaId</column-name><column-value><![CDATA[");
		sb.append(getIrudiKarpetaId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>irudia</column-name><column-value><![CDATA[");
		sb.append(getIrudia());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>irudiKopurua</column-name><column-value><![CDATA[");
		sb.append(getIrudiKopurua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>iruzkinKopurua</column-name><column-value><![CDATA[");
		sb.append(getIruzkinKopurua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>balorazioKopurua</column-name><column-value><![CDATA[");
		sb.append(getBalorazioKopurua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>balorazioenBB</column-name><column-value><![CDATA[");
		sb.append(getBalorazioenBB());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Sagardotegi.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			Sagardotegi.class
		};
	private long _sagardotegiId;
	private String _izena;
	private String _herria;
	private String _helbidea;
	private String _telefonoa;
	private String _emaila;
	private String _weborria;
	private double _lat;
	private double _lng;
	private long _edukiera;
	private long _irudiKarpetaId;
	private String _irudia;
	private long _irudiKopurua;
	private long _iruzkinKopurua;
	private long _balorazioKopurua;
	private double _balorazioenBB;
	private Date _createDate;
	private Date _modifiedDate;
	private Sagardotegi _escapedModelProxy;
}