/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package net.sareweb.txotx.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import net.sareweb.txotx.model.SagardoEgun;
import net.sareweb.txotx.model.SagardoEgunModel;
import net.sareweb.txotx.model.SagardoEgunSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the SagardoEgun service. Represents a row in the &quot;Txotx_SagardoEgun&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link net.sareweb.txotx.model.SagardoEgunModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SagardoEgunImpl}.
 * </p>
 *
 * @author A.Galdos
 * @see SagardoEgunImpl
 * @see net.sareweb.txotx.model.SagardoEgun
 * @see net.sareweb.txotx.model.SagardoEgunModel
 * @generated
 */
@JSON(strict = true)
public class SagardoEgunModelImpl extends BaseModelImpl<SagardoEgun>
	implements SagardoEgunModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a sagardo egun model instance should use the {@link net.sareweb.txotx.model.SagardoEgun} interface instead.
	 */
	public static final String TABLE_NAME = "Txotx_SagardoEgun";
	public static final Object[][] TABLE_COLUMNS = {
			{ "sagardoEgunId", Types.BIGINT },
			{ "izena", Types.VARCHAR },
			{ "edizioa", Types.BIGINT },
			{ "herria", Types.VARCHAR },
			{ "lekua", Types.VARCHAR },
			{ "emaila", Types.VARCHAR },
			{ "twitter", Types.VARCHAR },
			{ "weborria", Types.VARCHAR },
			{ "hasieraDate", Types.TIMESTAMP },
			{ "lat", Types.DOUBLE },
			{ "lng", Types.DOUBLE },
			{ "irudiKarpetaId", Types.BIGINT },
			{ "irudia", Types.VARCHAR },
			{ "irudiKopurua", Types.BIGINT },
			{ "iruzkinKopurua", Types.BIGINT },
			{ "balorazioKopurua", Types.BIGINT },
			{ "balorazioenBB", Types.DOUBLE },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "userId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table Txotx_SagardoEgun (sagardoEgunId LONG not null primary key,izena VARCHAR(75) null,edizioa LONG,herria VARCHAR(75) null,lekua VARCHAR(75) null,emaila VARCHAR(75) null,twitter VARCHAR(75) null,weborria VARCHAR(1000) null,hasieraDate DATE null,lat DOUBLE,lng DOUBLE,irudiKarpetaId LONG,irudia VARCHAR(75) null,irudiKopurua LONG,iruzkinKopurua LONG,balorazioKopurua LONG,balorazioenBB DOUBLE,createDate DATE null,modifiedDate DATE null,userId LONG)";
	public static final String TABLE_SQL_DROP = "drop table Txotx_SagardoEgun";
	public static final String ORDER_BY_JPQL = " ORDER BY sagardoEgun.createDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY Txotx_SagardoEgun.createDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.net.sareweb.txotx.model.SagardoEgun"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.net.sareweb.txotx.model.SagardoEgun"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static SagardoEgun toModel(SagardoEgunSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		SagardoEgun model = new SagardoEgunImpl();

		model.setSagardoEgunId(soapModel.getSagardoEgunId());
		model.setIzena(soapModel.getIzena());
		model.setEdizioa(soapModel.getEdizioa());
		model.setHerria(soapModel.getHerria());
		model.setLekua(soapModel.getLekua());
		model.setEmaila(soapModel.getEmaila());
		model.setTwitter(soapModel.getTwitter());
		model.setWeborria(soapModel.getWeborria());
		model.setHasieraDate(soapModel.getHasieraDate());
		model.setLat(soapModel.getLat());
		model.setLng(soapModel.getLng());
		model.setIrudiKarpetaId(soapModel.getIrudiKarpetaId());
		model.setIrudia(soapModel.getIrudia());
		model.setIrudiKopurua(soapModel.getIrudiKopurua());
		model.setIruzkinKopurua(soapModel.getIruzkinKopurua());
		model.setBalorazioKopurua(soapModel.getBalorazioKopurua());
		model.setBalorazioenBB(soapModel.getBalorazioenBB());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setUserId(soapModel.getUserId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<SagardoEgun> toModels(SagardoEgunSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<SagardoEgun> models = new ArrayList<SagardoEgun>(soapModels.length);

		for (SagardoEgunSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.net.sareweb.txotx.model.SagardoEgun"));

	public SagardoEgunModelImpl() {
	}

	public long getPrimaryKey() {
		return _sagardoEgunId;
	}

	public void setPrimaryKey(long primaryKey) {
		setSagardoEgunId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_sagardoEgunId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return SagardoEgun.class;
	}

	public String getModelClassName() {
		return SagardoEgun.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("sagardoEgunId", getSagardoEgunId());
		attributes.put("izena", getIzena());
		attributes.put("edizioa", getEdizioa());
		attributes.put("herria", getHerria());
		attributes.put("lekua", getLekua());
		attributes.put("emaila", getEmaila());
		attributes.put("twitter", getTwitter());
		attributes.put("weborria", getWeborria());
		attributes.put("hasieraDate", getHasieraDate());
		attributes.put("lat", getLat());
		attributes.put("lng", getLng());
		attributes.put("irudiKarpetaId", getIrudiKarpetaId());
		attributes.put("irudia", getIrudia());
		attributes.put("irudiKopurua", getIrudiKopurua());
		attributes.put("iruzkinKopurua", getIruzkinKopurua());
		attributes.put("balorazioKopurua", getBalorazioKopurua());
		attributes.put("balorazioenBB", getBalorazioenBB());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("userId", getUserId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long sagardoEgunId = (Long)attributes.get("sagardoEgunId");

		if (sagardoEgunId != null) {
			setSagardoEgunId(sagardoEgunId);
		}

		String izena = (String)attributes.get("izena");

		if (izena != null) {
			setIzena(izena);
		}

		Long edizioa = (Long)attributes.get("edizioa");

		if (edizioa != null) {
			setEdizioa(edizioa);
		}

		String herria = (String)attributes.get("herria");

		if (herria != null) {
			setHerria(herria);
		}

		String lekua = (String)attributes.get("lekua");

		if (lekua != null) {
			setLekua(lekua);
		}

		String emaila = (String)attributes.get("emaila");

		if (emaila != null) {
			setEmaila(emaila);
		}

		String twitter = (String)attributes.get("twitter");

		if (twitter != null) {
			setTwitter(twitter);
		}

		String weborria = (String)attributes.get("weborria");

		if (weborria != null) {
			setWeborria(weborria);
		}

		Date hasieraDate = (Date)attributes.get("hasieraDate");

		if (hasieraDate != null) {
			setHasieraDate(hasieraDate);
		}

		Double lat = (Double)attributes.get("lat");

		if (lat != null) {
			setLat(lat);
		}

		Double lng = (Double)attributes.get("lng");

		if (lng != null) {
			setLng(lng);
		}

		Long irudiKarpetaId = (Long)attributes.get("irudiKarpetaId");

		if (irudiKarpetaId != null) {
			setIrudiKarpetaId(irudiKarpetaId);
		}

		String irudia = (String)attributes.get("irudia");

		if (irudia != null) {
			setIrudia(irudia);
		}

		Long irudiKopurua = (Long)attributes.get("irudiKopurua");

		if (irudiKopurua != null) {
			setIrudiKopurua(irudiKopurua);
		}

		Long iruzkinKopurua = (Long)attributes.get("iruzkinKopurua");

		if (iruzkinKopurua != null) {
			setIruzkinKopurua(iruzkinKopurua);
		}

		Long balorazioKopurua = (Long)attributes.get("balorazioKopurua");

		if (balorazioKopurua != null) {
			setBalorazioKopurua(balorazioKopurua);
		}

		Double balorazioenBB = (Double)attributes.get("balorazioenBB");

		if (balorazioenBB != null) {
			setBalorazioenBB(balorazioenBB);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}
	}

	@JSON
	public long getSagardoEgunId() {
		return _sagardoEgunId;
	}

	public void setSagardoEgunId(long sagardoEgunId) {
		_sagardoEgunId = sagardoEgunId;
	}

	@JSON
	public String getIzena() {
		if (_izena == null) {
			return StringPool.BLANK;
		}
		else {
			return _izena;
		}
	}

	public void setIzena(String izena) {
		_izena = izena;
	}

	@JSON
	public long getEdizioa() {
		return _edizioa;
	}

	public void setEdizioa(long edizioa) {
		_edizioa = edizioa;
	}

	@JSON
	public String getHerria() {
		if (_herria == null) {
			return StringPool.BLANK;
		}
		else {
			return _herria;
		}
	}

	public void setHerria(String herria) {
		_herria = herria;
	}

	@JSON
	public String getLekua() {
		if (_lekua == null) {
			return StringPool.BLANK;
		}
		else {
			return _lekua;
		}
	}

	public void setLekua(String lekua) {
		_lekua = lekua;
	}

	@JSON
	public String getEmaila() {
		if (_emaila == null) {
			return StringPool.BLANK;
		}
		else {
			return _emaila;
		}
	}

	public void setEmaila(String emaila) {
		_emaila = emaila;
	}

	@JSON
	public String getTwitter() {
		if (_twitter == null) {
			return StringPool.BLANK;
		}
		else {
			return _twitter;
		}
	}

	public void setTwitter(String twitter) {
		_twitter = twitter;
	}

	@JSON
	public String getWeborria() {
		if (_weborria == null) {
			return StringPool.BLANK;
		}
		else {
			return _weborria;
		}
	}

	public void setWeborria(String weborria) {
		_weborria = weborria;
	}

	@JSON
	public Date getHasieraDate() {
		return _hasieraDate;
	}

	public void setHasieraDate(Date hasieraDate) {
		_hasieraDate = hasieraDate;
	}

	@JSON
	public double getLat() {
		return _lat;
	}

	public void setLat(double lat) {
		_lat = lat;
	}

	@JSON
	public double getLng() {
		return _lng;
	}

	public void setLng(double lng) {
		_lng = lng;
	}

	@JSON
	public long getIrudiKarpetaId() {
		return _irudiKarpetaId;
	}

	public void setIrudiKarpetaId(long irudiKarpetaId) {
		_irudiKarpetaId = irudiKarpetaId;
	}

	@JSON
	public String getIrudia() {
		if (_irudia == null) {
			return StringPool.BLANK;
		}
		else {
			return _irudia;
		}
	}

	public void setIrudia(String irudia) {
		_irudia = irudia;
	}

	@JSON
	public long getIrudiKopurua() {
		return _irudiKopurua;
	}

	public void setIrudiKopurua(long irudiKopurua) {
		_irudiKopurua = irudiKopurua;
	}

	@JSON
	public long getIruzkinKopurua() {
		return _iruzkinKopurua;
	}

	public void setIruzkinKopurua(long iruzkinKopurua) {
		_iruzkinKopurua = iruzkinKopurua;
	}

	@JSON
	public long getBalorazioKopurua() {
		return _balorazioKopurua;
	}

	public void setBalorazioKopurua(long balorazioKopurua) {
		_balorazioKopurua = balorazioKopurua;
	}

	@JSON
	public double getBalorazioenBB() {
		return _balorazioenBB;
	}

	public void setBalorazioenBB(double balorazioenBB) {
		_balorazioenBB = balorazioenBB;
	}

	@JSON
	public Date getCreateDate() {
		return _createDate;
	}

	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			SagardoEgun.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SagardoEgun toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (SagardoEgun)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		SagardoEgunImpl sagardoEgunImpl = new SagardoEgunImpl();

		sagardoEgunImpl.setSagardoEgunId(getSagardoEgunId());
		sagardoEgunImpl.setIzena(getIzena());
		sagardoEgunImpl.setEdizioa(getEdizioa());
		sagardoEgunImpl.setHerria(getHerria());
		sagardoEgunImpl.setLekua(getLekua());
		sagardoEgunImpl.setEmaila(getEmaila());
		sagardoEgunImpl.setTwitter(getTwitter());
		sagardoEgunImpl.setWeborria(getWeborria());
		sagardoEgunImpl.setHasieraDate(getHasieraDate());
		sagardoEgunImpl.setLat(getLat());
		sagardoEgunImpl.setLng(getLng());
		sagardoEgunImpl.setIrudiKarpetaId(getIrudiKarpetaId());
		sagardoEgunImpl.setIrudia(getIrudia());
		sagardoEgunImpl.setIrudiKopurua(getIrudiKopurua());
		sagardoEgunImpl.setIruzkinKopurua(getIruzkinKopurua());
		sagardoEgunImpl.setBalorazioKopurua(getBalorazioKopurua());
		sagardoEgunImpl.setBalorazioenBB(getBalorazioenBB());
		sagardoEgunImpl.setCreateDate(getCreateDate());
		sagardoEgunImpl.setModifiedDate(getModifiedDate());
		sagardoEgunImpl.setUserId(getUserId());

		sagardoEgunImpl.resetOriginalValues();

		return sagardoEgunImpl;
	}

	public int compareTo(SagardoEgun sagardoEgun) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(), sagardoEgun.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		SagardoEgun sagardoEgun = null;

		try {
			sagardoEgun = (SagardoEgun)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = sagardoEgun.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<SagardoEgun> toCacheModel() {
		SagardoEgunCacheModel sagardoEgunCacheModel = new SagardoEgunCacheModel();

		sagardoEgunCacheModel.sagardoEgunId = getSagardoEgunId();

		sagardoEgunCacheModel.izena = getIzena();

		String izena = sagardoEgunCacheModel.izena;

		if ((izena != null) && (izena.length() == 0)) {
			sagardoEgunCacheModel.izena = null;
		}

		sagardoEgunCacheModel.edizioa = getEdizioa();

		sagardoEgunCacheModel.herria = getHerria();

		String herria = sagardoEgunCacheModel.herria;

		if ((herria != null) && (herria.length() == 0)) {
			sagardoEgunCacheModel.herria = null;
		}

		sagardoEgunCacheModel.lekua = getLekua();

		String lekua = sagardoEgunCacheModel.lekua;

		if ((lekua != null) && (lekua.length() == 0)) {
			sagardoEgunCacheModel.lekua = null;
		}

		sagardoEgunCacheModel.emaila = getEmaila();

		String emaila = sagardoEgunCacheModel.emaila;

		if ((emaila != null) && (emaila.length() == 0)) {
			sagardoEgunCacheModel.emaila = null;
		}

		sagardoEgunCacheModel.twitter = getTwitter();

		String twitter = sagardoEgunCacheModel.twitter;

		if ((twitter != null) && (twitter.length() == 0)) {
			sagardoEgunCacheModel.twitter = null;
		}

		sagardoEgunCacheModel.weborria = getWeborria();

		String weborria = sagardoEgunCacheModel.weborria;

		if ((weborria != null) && (weborria.length() == 0)) {
			sagardoEgunCacheModel.weborria = null;
		}

		Date hasieraDate = getHasieraDate();

		if (hasieraDate != null) {
			sagardoEgunCacheModel.hasieraDate = hasieraDate.getTime();
		}
		else {
			sagardoEgunCacheModel.hasieraDate = Long.MIN_VALUE;
		}

		sagardoEgunCacheModel.lat = getLat();

		sagardoEgunCacheModel.lng = getLng();

		sagardoEgunCacheModel.irudiKarpetaId = getIrudiKarpetaId();

		sagardoEgunCacheModel.irudia = getIrudia();

		String irudia = sagardoEgunCacheModel.irudia;

		if ((irudia != null) && (irudia.length() == 0)) {
			sagardoEgunCacheModel.irudia = null;
		}

		sagardoEgunCacheModel.irudiKopurua = getIrudiKopurua();

		sagardoEgunCacheModel.iruzkinKopurua = getIruzkinKopurua();

		sagardoEgunCacheModel.balorazioKopurua = getBalorazioKopurua();

		sagardoEgunCacheModel.balorazioenBB = getBalorazioenBB();

		Date createDate = getCreateDate();

		if (createDate != null) {
			sagardoEgunCacheModel.createDate = createDate.getTime();
		}
		else {
			sagardoEgunCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			sagardoEgunCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			sagardoEgunCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		sagardoEgunCacheModel.userId = getUserId();

		return sagardoEgunCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(41);

		sb.append("{sagardoEgunId=");
		sb.append(getSagardoEgunId());
		sb.append(", izena=");
		sb.append(getIzena());
		sb.append(", edizioa=");
		sb.append(getEdizioa());
		sb.append(", herria=");
		sb.append(getHerria());
		sb.append(", lekua=");
		sb.append(getLekua());
		sb.append(", emaila=");
		sb.append(getEmaila());
		sb.append(", twitter=");
		sb.append(getTwitter());
		sb.append(", weborria=");
		sb.append(getWeborria());
		sb.append(", hasieraDate=");
		sb.append(getHasieraDate());
		sb.append(", lat=");
		sb.append(getLat());
		sb.append(", lng=");
		sb.append(getLng());
		sb.append(", irudiKarpetaId=");
		sb.append(getIrudiKarpetaId());
		sb.append(", irudia=");
		sb.append(getIrudia());
		sb.append(", irudiKopurua=");
		sb.append(getIrudiKopurua());
		sb.append(", iruzkinKopurua=");
		sb.append(getIruzkinKopurua());
		sb.append(", balorazioKopurua=");
		sb.append(getBalorazioKopurua());
		sb.append(", balorazioenBB=");
		sb.append(getBalorazioenBB());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(64);

		sb.append("<model><model-name>");
		sb.append("net.sareweb.txotx.model.SagardoEgun");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>sagardoEgunId</column-name><column-value><![CDATA[");
		sb.append(getSagardoEgunId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>izena</column-name><column-value><![CDATA[");
		sb.append(getIzena());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>edizioa</column-name><column-value><![CDATA[");
		sb.append(getEdizioa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>herria</column-name><column-value><![CDATA[");
		sb.append(getHerria());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lekua</column-name><column-value><![CDATA[");
		sb.append(getLekua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>emaila</column-name><column-value><![CDATA[");
		sb.append(getEmaila());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>twitter</column-name><column-value><![CDATA[");
		sb.append(getTwitter());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>weborria</column-name><column-value><![CDATA[");
		sb.append(getWeborria());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hasieraDate</column-name><column-value><![CDATA[");
		sb.append(getHasieraDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lat</column-name><column-value><![CDATA[");
		sb.append(getLat());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lng</column-name><column-value><![CDATA[");
		sb.append(getLng());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>irudiKarpetaId</column-name><column-value><![CDATA[");
		sb.append(getIrudiKarpetaId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>irudia</column-name><column-value><![CDATA[");
		sb.append(getIrudia());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>irudiKopurua</column-name><column-value><![CDATA[");
		sb.append(getIrudiKopurua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>iruzkinKopurua</column-name><column-value><![CDATA[");
		sb.append(getIruzkinKopurua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>balorazioKopurua</column-name><column-value><![CDATA[");
		sb.append(getBalorazioKopurua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>balorazioenBB</column-name><column-value><![CDATA[");
		sb.append(getBalorazioenBB());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = SagardoEgun.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			SagardoEgun.class
		};
	private long _sagardoEgunId;
	private String _izena;
	private long _edizioa;
	private String _herria;
	private String _lekua;
	private String _emaila;
	private String _twitter;
	private String _weborria;
	private Date _hasieraDate;
	private double _lat;
	private double _lng;
	private long _irudiKarpetaId;
	private String _irudia;
	private long _irudiKopurua;
	private long _iruzkinKopurua;
	private long _balorazioKopurua;
	private double _balorazioenBB;
	private Date _createDate;
	private Date _modifiedDate;
	private long _userId;
	private String _userUuid;
	private SagardoEgun _escapedModelProxy;
}