/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package net.sareweb.txotx.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the APKVersion service. Represents a row in the &quot;Txotx_APKVersion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link net.sareweb.txotx.model.impl.APKVersionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link net.sareweb.txotx.model.impl.APKVersionImpl}.
 * </p>
 *
 * @author A.Galdos
 * @see APKVersion
 * @see net.sareweb.txotx.model.impl.APKVersionImpl
 * @see net.sareweb.txotx.model.impl.APKVersionModelImpl
 * @generated
 */
public interface APKVersionModel extends BaseModel<APKVersion> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a a p k version model instance should use the {@link APKVersion} interface instead.
	 */

	/**
	 * Returns the primary key of this a p k version.
	 *
	 * @return the primary key of this a p k version
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this a p k version.
	 *
	 * @param primaryKey the primary key of this a p k version
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the apk version ID of this a p k version.
	 *
	 * @return the apk version ID of this a p k version
	 */
	public long getApkVersionId();

	/**
	 * Sets the apk version ID of this a p k version.
	 *
	 * @param apkVersionId the apk version ID of this a p k version
	 */
	public void setApkVersionId(long apkVersionId);

	/**
	 * Returns the supported min version of this a p k version.
	 *
	 * @return the supported min version of this a p k version
	 */
	public int getSupportedMinVersion();

	/**
	 * Sets the supported min version of this a p k version.
	 *
	 * @param supportedMinVersion the supported min version of this a p k version
	 */
	public void setSupportedMinVersion(int supportedMinVersion);

	/**
	 * Returns the supported min version name of this a p k version.
	 *
	 * @return the supported min version name of this a p k version
	 */
	@AutoEscape
	public String getSupportedMinVersionName();

	/**
	 * Sets the supported min version name of this a p k version.
	 *
	 * @param supportedMinVersionName the supported min version name of this a p k version
	 */
	public void setSupportedMinVersionName(String supportedMinVersionName);

	/**
	 * Returns the current version of this a p k version.
	 *
	 * @return the current version of this a p k version
	 */
	public int getCurrentVersion();

	/**
	 * Sets the current version of this a p k version.
	 *
	 * @param currentVersion the current version of this a p k version
	 */
	public void setCurrentVersion(int currentVersion);

	/**
	 * Returns the current version name of this a p k version.
	 *
	 * @return the current version name of this a p k version
	 */
	@AutoEscape
	public String getCurrentVersionName();

	/**
	 * Sets the current version name of this a p k version.
	 *
	 * @param currentVersionName the current version name of this a p k version
	 */
	public void setCurrentVersionName(String currentVersionName);

	/**
	 * Returns the create date of this a p k version.
	 *
	 * @return the create date of this a p k version
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this a p k version.
	 *
	 * @param createDate the create date of this a p k version
	 */
	public void setCreateDate(Date createDate);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(APKVersion apkVersion);

	public int hashCode();

	public CacheModel<APKVersion> toCacheModel();

	public APKVersion toEscapedModel();

	public String toString();

	public String toXmlString();
}