/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package net.sareweb.txotx.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Gertaera service. Represents a row in the &quot;Txotx_Gertaera&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link net.sareweb.txotx.model.impl.GertaeraModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link net.sareweb.txotx.model.impl.GertaeraImpl}.
 * </p>
 *
 * @author A.Galdos
 * @see Gertaera
 * @see net.sareweb.txotx.model.impl.GertaeraImpl
 * @see net.sareweb.txotx.model.impl.GertaeraModelImpl
 * @generated
 */
public interface GertaeraModel extends BaseModel<Gertaera> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a gertaera model instance should use the {@link Gertaera} interface instead.
	 */

	/**
	 * Returns the primary key of this gertaera.
	 *
	 * @return the primary key of this gertaera
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this gertaera.
	 *
	 * @param primaryKey the primary key of this gertaera
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the gertaera ID of this gertaera.
	 *
	 * @return the gertaera ID of this gertaera
	 */
	public long getGertaeraId();

	/**
	 * Sets the gertaera ID of this gertaera.
	 *
	 * @param gertaeraId the gertaera ID of this gertaera
	 */
	public void setGertaeraId(long gertaeraId);

	/**
	 * Returns the sagardotegi ID of this gertaera.
	 *
	 * @return the sagardotegi ID of this gertaera
	 */
	public long getSagardotegiId();

	/**
	 * Sets the sagardotegi ID of this gertaera.
	 *
	 * @param sagardotegiId the sagardotegi ID of this gertaera
	 */
	public void setSagardotegiId(long sagardotegiId);

	/**
	 * Returns the user ID of this gertaera.
	 *
	 * @return the user ID of this gertaera
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this gertaera.
	 *
	 * @param userId the user ID of this gertaera
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this gertaera.
	 *
	 * @return the user uuid of this gertaera
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this gertaera.
	 *
	 * @param userUuid the user uuid of this gertaera
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the screen name of this gertaera.
	 *
	 * @return the screen name of this gertaera
	 */
	@AutoEscape
	public String getScreenName();

	/**
	 * Sets the screen name of this gertaera.
	 *
	 * @param screenName the screen name of this gertaera
	 */
	public void setScreenName(String screenName);

	/**
	 * Returns the gertaera mota of this gertaera.
	 *
	 * @return the gertaera mota of this gertaera
	 */
	@AutoEscape
	public String getGertaeraMota();

	/**
	 * Sets the gertaera mota of this gertaera.
	 *
	 * @param gertaeraMota the gertaera mota of this gertaera
	 */
	public void setGertaeraMota(String gertaeraMota);

	/**
	 * Returns the testua of this gertaera.
	 *
	 * @return the testua of this gertaera
	 */
	@AutoEscape
	public String getTestua();

	/**
	 * Sets the testua of this gertaera.
	 *
	 * @param testua the testua of this gertaera
	 */
	public void setTestua(String testua);

	/**
	 * Returns the irudi karpeta ID of this gertaera.
	 *
	 * @return the irudi karpeta ID of this gertaera
	 */
	public long getIrudiKarpetaId();

	/**
	 * Sets the irudi karpeta ID of this gertaera.
	 *
	 * @param irudiKarpetaId the irudi karpeta ID of this gertaera
	 */
	public void setIrudiKarpetaId(long irudiKarpetaId);

	/**
	 * Returns the irudia of this gertaera.
	 *
	 * @return the irudia of this gertaera
	 */
	@AutoEscape
	public String getIrudia();

	/**
	 * Sets the irudia of this gertaera.
	 *
	 * @param irudia the irudia of this gertaera
	 */
	public void setIrudia(String irudia);

	/**
	 * Returns the balorazioa of this gertaera.
	 *
	 * @return the balorazioa of this gertaera
	 */
	public long getBalorazioa();

	/**
	 * Sets the balorazioa of this gertaera.
	 *
	 * @param balorazioa the balorazioa of this gertaera
	 */
	public void setBalorazioa(long balorazioa);

	/**
	 * Returns the create date of this gertaera.
	 *
	 * @return the create date of this gertaera
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this gertaera.
	 *
	 * @param createDate the create date of this gertaera
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this gertaera.
	 *
	 * @return the modified date of this gertaera
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this gertaera.
	 *
	 * @param modifiedDate the modified date of this gertaera
	 */
	public void setModifiedDate(Date modifiedDate);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Gertaera gertaera);

	public int hashCode();

	public CacheModel<Gertaera> toCacheModel();

	public Gertaera toEscapedModel();

	public String toString();

	public String toXmlString();
}