/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package net.sareweb.txotx.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Sagardotegi service. Represents a row in the &quot;Txotx_Sagardotegi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link net.sareweb.txotx.model.impl.SagardotegiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link net.sareweb.txotx.model.impl.SagardotegiImpl}.
 * </p>
 *
 * @author A.Galdos
 * @see Sagardotegi
 * @see net.sareweb.txotx.model.impl.SagardotegiImpl
 * @see net.sareweb.txotx.model.impl.SagardotegiModelImpl
 * @generated
 */
public interface SagardotegiModel extends BaseModel<Sagardotegi> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sagardotegi model instance should use the {@link Sagardotegi} interface instead.
	 */

	/**
	 * Returns the primary key of this sagardotegi.
	 *
	 * @return the primary key of this sagardotegi
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this sagardotegi.
	 *
	 * @param primaryKey the primary key of this sagardotegi
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the sagardotegi ID of this sagardotegi.
	 *
	 * @return the sagardotegi ID of this sagardotegi
	 */
	public long getSagardotegiId();

	/**
	 * Sets the sagardotegi ID of this sagardotegi.
	 *
	 * @param sagardotegiId the sagardotegi ID of this sagardotegi
	 */
	public void setSagardotegiId(long sagardotegiId);

	/**
	 * Returns the izena of this sagardotegi.
	 *
	 * @return the izena of this sagardotegi
	 */
	@AutoEscape
	public String getIzena();

	/**
	 * Sets the izena of this sagardotegi.
	 *
	 * @param izena the izena of this sagardotegi
	 */
	public void setIzena(String izena);

	/**
	 * Returns the herria of this sagardotegi.
	 *
	 * @return the herria of this sagardotegi
	 */
	@AutoEscape
	public String getHerria();

	/**
	 * Sets the herria of this sagardotegi.
	 *
	 * @param herria the herria of this sagardotegi
	 */
	public void setHerria(String herria);

	/**
	 * Returns the helbidea of this sagardotegi.
	 *
	 * @return the helbidea of this sagardotegi
	 */
	@AutoEscape
	public String getHelbidea();

	/**
	 * Sets the helbidea of this sagardotegi.
	 *
	 * @param helbidea the helbidea of this sagardotegi
	 */
	public void setHelbidea(String helbidea);

	/**
	 * Returns the telefonoa of this sagardotegi.
	 *
	 * @return the telefonoa of this sagardotegi
	 */
	@AutoEscape
	public String getTelefonoa();

	/**
	 * Sets the telefonoa of this sagardotegi.
	 *
	 * @param telefonoa the telefonoa of this sagardotegi
	 */
	public void setTelefonoa(String telefonoa);

	/**
	 * Returns the emaila of this sagardotegi.
	 *
	 * @return the emaila of this sagardotegi
	 */
	@AutoEscape
	public String getEmaila();

	/**
	 * Sets the emaila of this sagardotegi.
	 *
	 * @param emaila the emaila of this sagardotegi
	 */
	public void setEmaila(String emaila);

	/**
	 * Returns the twitter of this sagardotegi.
	 *
	 * @return the twitter of this sagardotegi
	 */
	@AutoEscape
	public String getTwitter();

	/**
	 * Sets the twitter of this sagardotegi.
	 *
	 * @param twitter the twitter of this sagardotegi
	 */
	public void setTwitter(String twitter);

	/**
	 * Returns the weborria of this sagardotegi.
	 *
	 * @return the weborria of this sagardotegi
	 */
	@AutoEscape
	public String getWeborria();

	/**
	 * Sets the weborria of this sagardotegi.
	 *
	 * @param weborria the weborria of this sagardotegi
	 */
	public void setWeborria(String weborria);

	/**
	 * Returns the lat of this sagardotegi.
	 *
	 * @return the lat of this sagardotegi
	 */
	public double getLat();

	/**
	 * Sets the lat of this sagardotegi.
	 *
	 * @param lat the lat of this sagardotegi
	 */
	public void setLat(double lat);

	/**
	 * Returns the lng of this sagardotegi.
	 *
	 * @return the lng of this sagardotegi
	 */
	public double getLng();

	/**
	 * Sets the lng of this sagardotegi.
	 *
	 * @param lng the lng of this sagardotegi
	 */
	public void setLng(double lng);

	/**
	 * Returns the edukiera of this sagardotegi.
	 *
	 * @return the edukiera of this sagardotegi
	 */
	public long getEdukiera();

	/**
	 * Sets the edukiera of this sagardotegi.
	 *
	 * @param edukiera the edukiera of this sagardotegi
	 */
	public void setEdukiera(long edukiera);

	/**
	 * Returns the irudi karpeta ID of this sagardotegi.
	 *
	 * @return the irudi karpeta ID of this sagardotegi
	 */
	public long getIrudiKarpetaId();

	/**
	 * Sets the irudi karpeta ID of this sagardotegi.
	 *
	 * @param irudiKarpetaId the irudi karpeta ID of this sagardotegi
	 */
	public void setIrudiKarpetaId(long irudiKarpetaId);

	/**
	 * Returns the irudia of this sagardotegi.
	 *
	 * @return the irudia of this sagardotegi
	 */
	@AutoEscape
	public String getIrudia();

	/**
	 * Sets the irudia of this sagardotegi.
	 *
	 * @param irudia the irudia of this sagardotegi
	 */
	public void setIrudia(String irudia);

	/**
	 * Returns the irudi kopurua of this sagardotegi.
	 *
	 * @return the irudi kopurua of this sagardotegi
	 */
	public long getIrudiKopurua();

	/**
	 * Sets the irudi kopurua of this sagardotegi.
	 *
	 * @param irudiKopurua the irudi kopurua of this sagardotegi
	 */
	public void setIrudiKopurua(long irudiKopurua);

	/**
	 * Returns the iruzkin kopurua of this sagardotegi.
	 *
	 * @return the iruzkin kopurua of this sagardotegi
	 */
	public long getIruzkinKopurua();

	/**
	 * Sets the iruzkin kopurua of this sagardotegi.
	 *
	 * @param iruzkinKopurua the iruzkin kopurua of this sagardotegi
	 */
	public void setIruzkinKopurua(long iruzkinKopurua);

	/**
	 * Returns the balorazio kopurua of this sagardotegi.
	 *
	 * @return the balorazio kopurua of this sagardotegi
	 */
	public long getBalorazioKopurua();

	/**
	 * Sets the balorazio kopurua of this sagardotegi.
	 *
	 * @param balorazioKopurua the balorazio kopurua of this sagardotegi
	 */
	public void setBalorazioKopurua(long balorazioKopurua);

	/**
	 * Returns the balorazioen b b of this sagardotegi.
	 *
	 * @return the balorazioen b b of this sagardotegi
	 */
	public double getBalorazioenBB();

	/**
	 * Sets the balorazioen b b of this sagardotegi.
	 *
	 * @param balorazioenBB the balorazioen b b of this sagardotegi
	 */
	public void setBalorazioenBB(double balorazioenBB);

	/**
	 * Returns the create date of this sagardotegi.
	 *
	 * @return the create date of this sagardotegi
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this sagardotegi.
	 *
	 * @param createDate the create date of this sagardotegi
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this sagardotegi.
	 *
	 * @return the modified date of this sagardotegi
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this sagardotegi.
	 *
	 * @param modifiedDate the modified date of this sagardotegi
	 */
	public void setModifiedDate(Date modifiedDate);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Sagardotegi sagardotegi);

	public int hashCode();

	public CacheModel<Sagardotegi> toCacheModel();

	public Sagardotegi toEscapedModel();

	public String toString();

	public String toXmlString();
}