/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package net.sareweb.txotx.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SagardoEgun service. Represents a row in the &quot;Txotx_SagardoEgun&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link net.sareweb.txotx.model.impl.SagardoEgunModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link net.sareweb.txotx.model.impl.SagardoEgunImpl}.
 * </p>
 *
 * @author A.Galdos
 * @see SagardoEgun
 * @see net.sareweb.txotx.model.impl.SagardoEgunImpl
 * @see net.sareweb.txotx.model.impl.SagardoEgunModelImpl
 * @generated
 */
public interface SagardoEgunModel extends BaseModel<SagardoEgun> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sagardo egun model instance should use the {@link SagardoEgun} interface instead.
	 */

	/**
	 * Returns the primary key of this sagardo egun.
	 *
	 * @return the primary key of this sagardo egun
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this sagardo egun.
	 *
	 * @param primaryKey the primary key of this sagardo egun
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the sagardo egun ID of this sagardo egun.
	 *
	 * @return the sagardo egun ID of this sagardo egun
	 */
	public long getSagardoEgunId();

	/**
	 * Sets the sagardo egun ID of this sagardo egun.
	 *
	 * @param sagardoEgunId the sagardo egun ID of this sagardo egun
	 */
	public void setSagardoEgunId(long sagardoEgunId);

	/**
	 * Returns the izena of this sagardo egun.
	 *
	 * @return the izena of this sagardo egun
	 */
	@AutoEscape
	public String getIzena();

	/**
	 * Sets the izena of this sagardo egun.
	 *
	 * @param izena the izena of this sagardo egun
	 */
	public void setIzena(String izena);

	/**
	 * Returns the edizioa of this sagardo egun.
	 *
	 * @return the edizioa of this sagardo egun
	 */
	public long getEdizioa();

	/**
	 * Sets the edizioa of this sagardo egun.
	 *
	 * @param edizioa the edizioa of this sagardo egun
	 */
	public void setEdizioa(long edizioa);

	/**
	 * Returns the herria of this sagardo egun.
	 *
	 * @return the herria of this sagardo egun
	 */
	@AutoEscape
	public String getHerria();

	/**
	 * Sets the herria of this sagardo egun.
	 *
	 * @param herria the herria of this sagardo egun
	 */
	public void setHerria(String herria);

	/**
	 * Returns the lekua of this sagardo egun.
	 *
	 * @return the lekua of this sagardo egun
	 */
	@AutoEscape
	public String getLekua();

	/**
	 * Sets the lekua of this sagardo egun.
	 *
	 * @param lekua the lekua of this sagardo egun
	 */
	public void setLekua(String lekua);

	/**
	 * Returns the emaila of this sagardo egun.
	 *
	 * @return the emaila of this sagardo egun
	 */
	@AutoEscape
	public String getEmaila();

	/**
	 * Sets the emaila of this sagardo egun.
	 *
	 * @param emaila the emaila of this sagardo egun
	 */
	public void setEmaila(String emaila);

	/**
	 * Returns the twitter of this sagardo egun.
	 *
	 * @return the twitter of this sagardo egun
	 */
	@AutoEscape
	public String getTwitter();

	/**
	 * Sets the twitter of this sagardo egun.
	 *
	 * @param twitter the twitter of this sagardo egun
	 */
	public void setTwitter(String twitter);

	/**
	 * Returns the weborria of this sagardo egun.
	 *
	 * @return the weborria of this sagardo egun
	 */
	@AutoEscape
	public String getWeborria();

	/**
	 * Sets the weborria of this sagardo egun.
	 *
	 * @param weborria the weborria of this sagardo egun
	 */
	public void setWeborria(String weborria);

	/**
	 * Returns the hasiera date of this sagardo egun.
	 *
	 * @return the hasiera date of this sagardo egun
	 */
	public Date getHasieraDate();

	/**
	 * Sets the hasiera date of this sagardo egun.
	 *
	 * @param hasieraDate the hasiera date of this sagardo egun
	 */
	public void setHasieraDate(Date hasieraDate);

	/**
	 * Returns the lat of this sagardo egun.
	 *
	 * @return the lat of this sagardo egun
	 */
	public double getLat();

	/**
	 * Sets the lat of this sagardo egun.
	 *
	 * @param lat the lat of this sagardo egun
	 */
	public void setLat(double lat);

	/**
	 * Returns the lng of this sagardo egun.
	 *
	 * @return the lng of this sagardo egun
	 */
	public double getLng();

	/**
	 * Sets the lng of this sagardo egun.
	 *
	 * @param lng the lng of this sagardo egun
	 */
	public void setLng(double lng);

	/**
	 * Returns the irudi karpeta ID of this sagardo egun.
	 *
	 * @return the irudi karpeta ID of this sagardo egun
	 */
	public long getIrudiKarpetaId();

	/**
	 * Sets the irudi karpeta ID of this sagardo egun.
	 *
	 * @param irudiKarpetaId the irudi karpeta ID of this sagardo egun
	 */
	public void setIrudiKarpetaId(long irudiKarpetaId);

	/**
	 * Returns the irudia of this sagardo egun.
	 *
	 * @return the irudia of this sagardo egun
	 */
	@AutoEscape
	public String getIrudia();

	/**
	 * Sets the irudia of this sagardo egun.
	 *
	 * @param irudia the irudia of this sagardo egun
	 */
	public void setIrudia(String irudia);

	/**
	 * Returns the irudi kopurua of this sagardo egun.
	 *
	 * @return the irudi kopurua of this sagardo egun
	 */
	public long getIrudiKopurua();

	/**
	 * Sets the irudi kopurua of this sagardo egun.
	 *
	 * @param irudiKopurua the irudi kopurua of this sagardo egun
	 */
	public void setIrudiKopurua(long irudiKopurua);

	/**
	 * Returns the iruzkin kopurua of this sagardo egun.
	 *
	 * @return the iruzkin kopurua of this sagardo egun
	 */
	public long getIruzkinKopurua();

	/**
	 * Sets the iruzkin kopurua of this sagardo egun.
	 *
	 * @param iruzkinKopurua the iruzkin kopurua of this sagardo egun
	 */
	public void setIruzkinKopurua(long iruzkinKopurua);

	/**
	 * Returns the balorazio kopurua of this sagardo egun.
	 *
	 * @return the balorazio kopurua of this sagardo egun
	 */
	public long getBalorazioKopurua();

	/**
	 * Sets the balorazio kopurua of this sagardo egun.
	 *
	 * @param balorazioKopurua the balorazio kopurua of this sagardo egun
	 */
	public void setBalorazioKopurua(long balorazioKopurua);

	/**
	 * Returns the balorazioen b b of this sagardo egun.
	 *
	 * @return the balorazioen b b of this sagardo egun
	 */
	public double getBalorazioenBB();

	/**
	 * Sets the balorazioen b b of this sagardo egun.
	 *
	 * @param balorazioenBB the balorazioen b b of this sagardo egun
	 */
	public void setBalorazioenBB(double balorazioenBB);

	/**
	 * Returns the create date of this sagardo egun.
	 *
	 * @return the create date of this sagardo egun
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this sagardo egun.
	 *
	 * @param createDate the create date of this sagardo egun
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this sagardo egun.
	 *
	 * @return the modified date of this sagardo egun
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this sagardo egun.
	 *
	 * @param modifiedDate the modified date of this sagardo egun
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the user ID of this sagardo egun.
	 *
	 * @return the user ID of this sagardo egun
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this sagardo egun.
	 *
	 * @param userId the user ID of this sagardo egun
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this sagardo egun.
	 *
	 * @return the user uuid of this sagardo egun
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this sagardo egun.
	 *
	 * @param userUuid the user uuid of this sagardo egun
	 */
	public void setUserUuid(String userUuid);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(SagardoEgun sagardoEgun);

	public int hashCode();

	public CacheModel<SagardoEgun> toCacheModel();

	public SagardoEgun toEscapedModel();

	public String toString();

	public String toXmlString();
}