/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package net.sareweb.txotx.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import net.sareweb.txotx.model.Gertaera;
import net.sareweb.txotx.service.GertaeraLocalService;
import net.sareweb.txotx.service.GertaeraService;
import net.sareweb.txotx.service.GoogleDeviceLocalService;
import net.sareweb.txotx.service.GoogleDeviceService;
import net.sareweb.txotx.service.JarraipenLocalService;
import net.sareweb.txotx.service.JarraipenService;
import net.sareweb.txotx.service.OharraLocalService;
import net.sareweb.txotx.service.OharraService;
import net.sareweb.txotx.service.SagardoEgunLocalService;
import net.sareweb.txotx.service.SagardoEgunService;
import net.sareweb.txotx.service.SagardotegiLocalService;
import net.sareweb.txotx.service.SagardotegiService;
import net.sareweb.txotx.service.SailkapenaLocalService;
import net.sareweb.txotx.service.SailkapenaService;
import net.sareweb.txotx.service.persistence.GertaeraPersistence;
import net.sareweb.txotx.service.persistence.GoogleDevicePersistence;
import net.sareweb.txotx.service.persistence.JarraipenPersistence;
import net.sareweb.txotx.service.persistence.OharraPersistence;
import net.sareweb.txotx.service.persistence.SagardoEgunPersistence;
import net.sareweb.txotx.service.persistence.SagardotegiPersistence;
import net.sareweb.txotx.service.persistence.SailkapenaPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the gertaera local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link net.sareweb.txotx.service.impl.GertaeraLocalServiceImpl}.
 * </p>
 *
 * @author A.Galdos
 * @see net.sareweb.txotx.service.impl.GertaeraLocalServiceImpl
 * @see net.sareweb.txotx.service.GertaeraLocalServiceUtil
 * @generated
 */
public abstract class GertaeraLocalServiceBaseImpl extends BaseLocalServiceImpl
	implements GertaeraLocalService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link net.sareweb.txotx.service.GertaeraLocalServiceUtil} to access the gertaera local service.
	 */

	/**
	 * Adds the gertaera to the database. Also notifies the appropriate model listeners.
	 *
	 * @param gertaera the gertaera
	 * @return the gertaera that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public Gertaera addGertaera(Gertaera gertaera) throws SystemException {
		gertaera.setNew(true);

		return gertaeraPersistence.update(gertaera, false);
	}

	/**
	 * Creates a new gertaera with the primary key. Does not add the gertaera to the database.
	 *
	 * @param gertaeraId the primary key for the new gertaera
	 * @return the new gertaera
	 */
	public Gertaera createGertaera(long gertaeraId) {
		return gertaeraPersistence.create(gertaeraId);
	}

	/**
	 * Deletes the gertaera with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param gertaeraId the primary key of the gertaera
	 * @return the gertaera that was removed
	 * @throws PortalException if a gertaera with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public Gertaera deleteGertaera(long gertaeraId)
		throws PortalException, SystemException {
		return gertaeraPersistence.remove(gertaeraId);
	}

	/**
	 * Deletes the gertaera from the database. Also notifies the appropriate model listeners.
	 *
	 * @param gertaera the gertaera
	 * @return the gertaera that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public Gertaera deleteGertaera(Gertaera gertaera) throws SystemException {
		return gertaeraPersistence.remove(gertaera);
	}

	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(Gertaera.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return gertaeraPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return gertaeraPersistence.findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return gertaeraPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return gertaeraPersistence.countWithDynamicQuery(dynamicQuery);
	}

	public Gertaera fetchGertaera(long gertaeraId) throws SystemException {
		return gertaeraPersistence.fetchByPrimaryKey(gertaeraId);
	}

	/**
	 * Returns the gertaera with the primary key.
	 *
	 * @param gertaeraId the primary key of the gertaera
	 * @return the gertaera
	 * @throws PortalException if a gertaera with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public Gertaera getGertaera(long gertaeraId)
		throws PortalException, SystemException {
		return gertaeraPersistence.findByPrimaryKey(gertaeraId);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return gertaeraPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the gertaeras.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of gertaeras
	 * @param end the upper bound of the range of gertaeras (not inclusive)
	 * @return the range of gertaeras
	 * @throws SystemException if a system exception occurred
	 */
	public List<Gertaera> getGertaeras(int start, int end)
		throws SystemException {
		return gertaeraPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of gertaeras.
	 *
	 * @return the number of gertaeras
	 * @throws SystemException if a system exception occurred
	 */
	public int getGertaerasCount() throws SystemException {
		return gertaeraPersistence.countAll();
	}

	/**
	 * Updates the gertaera in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param gertaera the gertaera
	 * @return the gertaera that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public Gertaera updateGertaera(Gertaera gertaera) throws SystemException {
		return updateGertaera(gertaera, true);
	}

	/**
	 * Updates the gertaera in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param gertaera the gertaera
	 * @param merge whether to merge the gertaera with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the gertaera that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public Gertaera updateGertaera(Gertaera gertaera, boolean merge)
		throws SystemException {
		gertaera.setNew(false);

		return gertaeraPersistence.update(gertaera, merge);
	}

	/**
	 * Returns the gertaera local service.
	 *
	 * @return the gertaera local service
	 */
	public GertaeraLocalService getGertaeraLocalService() {
		return gertaeraLocalService;
	}

	/**
	 * Sets the gertaera local service.
	 *
	 * @param gertaeraLocalService the gertaera local service
	 */
	public void setGertaeraLocalService(
		GertaeraLocalService gertaeraLocalService) {
		this.gertaeraLocalService = gertaeraLocalService;
	}

	/**
	 * Returns the gertaera remote service.
	 *
	 * @return the gertaera remote service
	 */
	public GertaeraService getGertaeraService() {
		return gertaeraService;
	}

	/**
	 * Sets the gertaera remote service.
	 *
	 * @param gertaeraService the gertaera remote service
	 */
	public void setGertaeraService(GertaeraService gertaeraService) {
		this.gertaeraService = gertaeraService;
	}

	/**
	 * Returns the gertaera persistence.
	 *
	 * @return the gertaera persistence
	 */
	public GertaeraPersistence getGertaeraPersistence() {
		return gertaeraPersistence;
	}

	/**
	 * Sets the gertaera persistence.
	 *
	 * @param gertaeraPersistence the gertaera persistence
	 */
	public void setGertaeraPersistence(GertaeraPersistence gertaeraPersistence) {
		this.gertaeraPersistence = gertaeraPersistence;
	}

	/**
	 * Returns the google device local service.
	 *
	 * @return the google device local service
	 */
	public GoogleDeviceLocalService getGoogleDeviceLocalService() {
		return googleDeviceLocalService;
	}

	/**
	 * Sets the google device local service.
	 *
	 * @param googleDeviceLocalService the google device local service
	 */
	public void setGoogleDeviceLocalService(
		GoogleDeviceLocalService googleDeviceLocalService) {
		this.googleDeviceLocalService = googleDeviceLocalService;
	}

	/**
	 * Returns the google device remote service.
	 *
	 * @return the google device remote service
	 */
	public GoogleDeviceService getGoogleDeviceService() {
		return googleDeviceService;
	}

	/**
	 * Sets the google device remote service.
	 *
	 * @param googleDeviceService the google device remote service
	 */
	public void setGoogleDeviceService(GoogleDeviceService googleDeviceService) {
		this.googleDeviceService = googleDeviceService;
	}

	/**
	 * Returns the google device persistence.
	 *
	 * @return the google device persistence
	 */
	public GoogleDevicePersistence getGoogleDevicePersistence() {
		return googleDevicePersistence;
	}

	/**
	 * Sets the google device persistence.
	 *
	 * @param googleDevicePersistence the google device persistence
	 */
	public void setGoogleDevicePersistence(
		GoogleDevicePersistence googleDevicePersistence) {
		this.googleDevicePersistence = googleDevicePersistence;
	}

	/**
	 * Returns the jarraipen local service.
	 *
	 * @return the jarraipen local service
	 */
	public JarraipenLocalService getJarraipenLocalService() {
		return jarraipenLocalService;
	}

	/**
	 * Sets the jarraipen local service.
	 *
	 * @param jarraipenLocalService the jarraipen local service
	 */
	public void setJarraipenLocalService(
		JarraipenLocalService jarraipenLocalService) {
		this.jarraipenLocalService = jarraipenLocalService;
	}

	/**
	 * Returns the jarraipen remote service.
	 *
	 * @return the jarraipen remote service
	 */
	public JarraipenService getJarraipenService() {
		return jarraipenService;
	}

	/**
	 * Sets the jarraipen remote service.
	 *
	 * @param jarraipenService the jarraipen remote service
	 */
	public void setJarraipenService(JarraipenService jarraipenService) {
		this.jarraipenService = jarraipenService;
	}

	/**
	 * Returns the jarraipen persistence.
	 *
	 * @return the jarraipen persistence
	 */
	public JarraipenPersistence getJarraipenPersistence() {
		return jarraipenPersistence;
	}

	/**
	 * Sets the jarraipen persistence.
	 *
	 * @param jarraipenPersistence the jarraipen persistence
	 */
	public void setJarraipenPersistence(
		JarraipenPersistence jarraipenPersistence) {
		this.jarraipenPersistence = jarraipenPersistence;
	}

	/**
	 * Returns the oharra local service.
	 *
	 * @return the oharra local service
	 */
	public OharraLocalService getOharraLocalService() {
		return oharraLocalService;
	}

	/**
	 * Sets the oharra local service.
	 *
	 * @param oharraLocalService the oharra local service
	 */
	public void setOharraLocalService(OharraLocalService oharraLocalService) {
		this.oharraLocalService = oharraLocalService;
	}

	/**
	 * Returns the oharra remote service.
	 *
	 * @return the oharra remote service
	 */
	public OharraService getOharraService() {
		return oharraService;
	}

	/**
	 * Sets the oharra remote service.
	 *
	 * @param oharraService the oharra remote service
	 */
	public void setOharraService(OharraService oharraService) {
		this.oharraService = oharraService;
	}

	/**
	 * Returns the oharra persistence.
	 *
	 * @return the oharra persistence
	 */
	public OharraPersistence getOharraPersistence() {
		return oharraPersistence;
	}

	/**
	 * Sets the oharra persistence.
	 *
	 * @param oharraPersistence the oharra persistence
	 */
	public void setOharraPersistence(OharraPersistence oharraPersistence) {
		this.oharraPersistence = oharraPersistence;
	}

	/**
	 * Returns the sagardo egun local service.
	 *
	 * @return the sagardo egun local service
	 */
	public SagardoEgunLocalService getSagardoEgunLocalService() {
		return sagardoEgunLocalService;
	}

	/**
	 * Sets the sagardo egun local service.
	 *
	 * @param sagardoEgunLocalService the sagardo egun local service
	 */
	public void setSagardoEgunLocalService(
		SagardoEgunLocalService sagardoEgunLocalService) {
		this.sagardoEgunLocalService = sagardoEgunLocalService;
	}

	/**
	 * Returns the sagardo egun remote service.
	 *
	 * @return the sagardo egun remote service
	 */
	public SagardoEgunService getSagardoEgunService() {
		return sagardoEgunService;
	}

	/**
	 * Sets the sagardo egun remote service.
	 *
	 * @param sagardoEgunService the sagardo egun remote service
	 */
	public void setSagardoEgunService(SagardoEgunService sagardoEgunService) {
		this.sagardoEgunService = sagardoEgunService;
	}

	/**
	 * Returns the sagardo egun persistence.
	 *
	 * @return the sagardo egun persistence
	 */
	public SagardoEgunPersistence getSagardoEgunPersistence() {
		return sagardoEgunPersistence;
	}

	/**
	 * Sets the sagardo egun persistence.
	 *
	 * @param sagardoEgunPersistence the sagardo egun persistence
	 */
	public void setSagardoEgunPersistence(
		SagardoEgunPersistence sagardoEgunPersistence) {
		this.sagardoEgunPersistence = sagardoEgunPersistence;
	}

	/**
	 * Returns the sagardotegi local service.
	 *
	 * @return the sagardotegi local service
	 */
	public SagardotegiLocalService getSagardotegiLocalService() {
		return sagardotegiLocalService;
	}

	/**
	 * Sets the sagardotegi local service.
	 *
	 * @param sagardotegiLocalService the sagardotegi local service
	 */
	public void setSagardotegiLocalService(
		SagardotegiLocalService sagardotegiLocalService) {
		this.sagardotegiLocalService = sagardotegiLocalService;
	}

	/**
	 * Returns the sagardotegi remote service.
	 *
	 * @return the sagardotegi remote service
	 */
	public SagardotegiService getSagardotegiService() {
		return sagardotegiService;
	}

	/**
	 * Sets the sagardotegi remote service.
	 *
	 * @param sagardotegiService the sagardotegi remote service
	 */
	public void setSagardotegiService(SagardotegiService sagardotegiService) {
		this.sagardotegiService = sagardotegiService;
	}

	/**
	 * Returns the sagardotegi persistence.
	 *
	 * @return the sagardotegi persistence
	 */
	public SagardotegiPersistence getSagardotegiPersistence() {
		return sagardotegiPersistence;
	}

	/**
	 * Sets the sagardotegi persistence.
	 *
	 * @param sagardotegiPersistence the sagardotegi persistence
	 */
	public void setSagardotegiPersistence(
		SagardotegiPersistence sagardotegiPersistence) {
		this.sagardotegiPersistence = sagardotegiPersistence;
	}

	/**
	 * Returns the sailkapena local service.
	 *
	 * @return the sailkapena local service
	 */
	public SailkapenaLocalService getSailkapenaLocalService() {
		return sailkapenaLocalService;
	}

	/**
	 * Sets the sailkapena local service.
	 *
	 * @param sailkapenaLocalService the sailkapena local service
	 */
	public void setSailkapenaLocalService(
		SailkapenaLocalService sailkapenaLocalService) {
		this.sailkapenaLocalService = sailkapenaLocalService;
	}

	/**
	 * Returns the sailkapena remote service.
	 *
	 * @return the sailkapena remote service
	 */
	public SailkapenaService getSailkapenaService() {
		return sailkapenaService;
	}

	/**
	 * Sets the sailkapena remote service.
	 *
	 * @param sailkapenaService the sailkapena remote service
	 */
	public void setSailkapenaService(SailkapenaService sailkapenaService) {
		this.sailkapenaService = sailkapenaService;
	}

	/**
	 * Returns the sailkapena persistence.
	 *
	 * @return the sailkapena persistence
	 */
	public SailkapenaPersistence getSailkapenaPersistence() {
		return sailkapenaPersistence;
	}

	/**
	 * Sets the sailkapena persistence.
	 *
	 * @param sailkapenaPersistence the sailkapena persistence
	 */
	public void setSailkapenaPersistence(
		SailkapenaPersistence sailkapenaPersistence) {
		this.sailkapenaPersistence = sailkapenaPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("net.sareweb.txotx.model.Gertaera",
			gertaeraLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"net.sareweb.txotx.model.Gertaera");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
	}

	protected Class<?> getModelClass() {
		return Gertaera.class;
	}

	protected String getModelClassName() {
		return Gertaera.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = gertaeraPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = GertaeraLocalService.class)
	protected GertaeraLocalService gertaeraLocalService;
	@BeanReference(type = GertaeraService.class)
	protected GertaeraService gertaeraService;
	@BeanReference(type = GertaeraPersistence.class)
	protected GertaeraPersistence gertaeraPersistence;
	@BeanReference(type = GoogleDeviceLocalService.class)
	protected GoogleDeviceLocalService googleDeviceLocalService;
	@BeanReference(type = GoogleDeviceService.class)
	protected GoogleDeviceService googleDeviceService;
	@BeanReference(type = GoogleDevicePersistence.class)
	protected GoogleDevicePersistence googleDevicePersistence;
	@BeanReference(type = JarraipenLocalService.class)
	protected JarraipenLocalService jarraipenLocalService;
	@BeanReference(type = JarraipenService.class)
	protected JarraipenService jarraipenService;
	@BeanReference(type = JarraipenPersistence.class)
	protected JarraipenPersistence jarraipenPersistence;
	@BeanReference(type = OharraLocalService.class)
	protected OharraLocalService oharraLocalService;
	@BeanReference(type = OharraService.class)
	protected OharraService oharraService;
	@BeanReference(type = OharraPersistence.class)
	protected OharraPersistence oharraPersistence;
	@BeanReference(type = SagardoEgunLocalService.class)
	protected SagardoEgunLocalService sagardoEgunLocalService;
	@BeanReference(type = SagardoEgunService.class)
	protected SagardoEgunService sagardoEgunService;
	@BeanReference(type = SagardoEgunPersistence.class)
	protected SagardoEgunPersistence sagardoEgunPersistence;
	@BeanReference(type = SagardotegiLocalService.class)
	protected SagardotegiLocalService sagardotegiLocalService;
	@BeanReference(type = SagardotegiService.class)
	protected SagardotegiService sagardotegiService;
	@BeanReference(type = SagardotegiPersistence.class)
	protected SagardotegiPersistence sagardotegiPersistence;
	@BeanReference(type = SailkapenaLocalService.class)
	protected SailkapenaLocalService sailkapenaLocalService;
	@BeanReference(type = SailkapenaService.class)
	protected SailkapenaService sailkapenaService;
	@BeanReference(type = SailkapenaPersistence.class)
	protected SailkapenaPersistence sailkapenaPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private GertaeraLocalServiceClpInvoker _clpInvoker = new GertaeraLocalServiceClpInvoker();
}